spring.application.name=kanbanApp
spring.datasource.url=jdbc:postgresql://localhost:5432/kanban_db
spring.datasource.username=kanban_user
spring.datasource.password=kanban_pass
spring.jpa.hibernate.ddl-auto=update